///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModel {
/*
{
  "state": "",
  "country": "",
  "phone": "1234567890",
  "vendor_id": "",
  "email": "dev@gmail.com",
  "avatar_url": "/user-avatar.png",
  "status": "active",
  "id": "cb884a3e-48a5-4437-a6f3-83e3fd0d63a4",
  "user_id": "CAV4",
  "name": "Dev",
  "warehouse": "",
  "location": "",
  "department": " ",
  "dob": "2022-06-24T06:27:10.055Z",
  "doj": "2022-06-24T06:27:10.055Z",
  "dodj": "2022-06-24T06:27:10.055Z",
  "role": "employee",
  "username": "cav4",
  "team": "Other",
  "company": "Other",
  "provider": null,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNiODg0YTNlLTQ4YTUtNDQzNy1hNmYzLTgzZTNmZDBkNjNhNCIsIm5hbWUiOiJEZXYiLCJyb2xlIjoiZW1wbG95ZWUiLCJpYXQiOjE2NTYwNTIyMTMsImV4cCI6MTY1NjA5NTQxM30.kqYNAUIhQrIP7Yx4mCI_JIioLgRc5veW4F0meLU8U80"
} 
*/

  String? state;
  String? country;
  String? phone;
  String? vendorId;
  String? email;
  String? avatarUrl;
  String? status;
  String? id;
  String? userId;
  String? name;
  String? warehouse;
  String? location;
  String? department;
  String? dob;
  String? doj;
  String? dodj;
  String? role;
  String? username;
  String? team;
  String? company;
  String? provider;
  String? token;

  UserModel({
    this.state,
    this.country,
    this.phone,
    this.vendorId,
    this.email,
    this.avatarUrl,
    this.status,
    this.id,
    this.userId,
    this.name,
    this.warehouse,
    this.location,
    this.department,
    this.dob,
    this.doj,
    this.dodj,
    this.role,
    this.username,
    this.team,
    this.company,
    this.provider,
    this.token,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    state = json['state']?.toString();
    country = json['country']?.toString();
    phone = json['phone']?.toString();
    vendorId = json['vendor_id']?.toString();
    email = json['email']?.toString();
    avatarUrl = json['avatar_url']?.toString();
    status = json['status']?.toString();
    id = json['id']?.toString();
    userId = json['user_id']?.toString();
    name = json['name']?.toString();
    warehouse = json['warehouse']?.toString();
    location = json['location']?.toString();
    department = json['department']?.toString();
    dob = json['dob']?.toString();
    doj = json['doj']?.toString();
    dodj = json['dodj']?.toString();
    role = json['role']?.toString();
    username = json['username']?.toString();
    team = json['team']?.toString();
    company = json['company']?.toString();
    provider = json['provider']?.toString();
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['state'] = state;
    data['country'] = country;
    data['phone'] = phone;
    data['vendor_id'] = vendorId;
    data['email'] = email;
    data['avatar_url'] = avatarUrl;
    data['status'] = status;
    data['id'] = id;
    data['user_id'] = userId;
    data['name'] = name;
    data['warehouse'] = warehouse;
    data['location'] = location;
    data['department'] = department;
    data['dob'] = dob;
    data['doj'] = doj;
    data['dodj'] = dodj;
    data['role'] = role;
    data['username'] = username;
    data['team'] = team;
    data['company'] = company;
    data['provider'] = provider;
    data['token'] = token;
    return data;
  }
}
